version: '3.3'

services:
  postgres:
    image: timescale/timescaledb:2.1.0-pg13
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  grafana:
    image: grafana/grafana:8.0.5
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data: {}
  grafana-data: {}
